-- CREATE TABLE `programa` (
--   `id` varchar(36) NOT NULL,
--   `createdBy` varchar(36) DEFAULT 'mam',
--   `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
--   `lastUpdatedBy` varchar(36) DEFAULT 'mam',
--   `lastUpdatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
--   `codPro` varchar(10) NOT NULL,
--   `descripcionAyto` varchar(255) DEFAULT NULL,
--   `descripcionOCM` varchar(255) NOT NULL,
--   `WebOCM` varchar(255) DEFAULT NULL,
--   `proCreatedDate` datetime DEFAULT NULL,
--   `proDeletedDate` datetime DEFAULT NULL,
--   `uso` varchar(255) DEFAULT NULL,
--   `observaciones` varchar(255) DEFAULT NULL,
--   `codOrg` varchar(10) DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) 